hooklib_lib = static_library(
    'hooklib',
    include_directories : inc,
    implicit_include_directories : false,
    dependencies : [
        capnhook.get_variable('hook_dep'),
        ws2_32_lib
    ],
    sources : [
        'cursor.c',
        'cursor.h',
        'config.c',
        'config.h',
        'createprocess.c',
        'createprocess.h',
        'dll.c',
        'dll.h',
        'dns.c',
        'dns.h',
        'dvd.c',
        'dvd.h',
        'fdshark.c',
        'fdshark.h',
        'imageutil.c',
        'imageutil.h',
        'path.c',
        'path.h',
        'reg.c',
        'reg.h',
        'setupapi.c',
        'setupapi.h',
        'spike.c',
        'spike.h',
        'touch.c',
        'touch.h',
        'printer_chc.c',
        'printer_chc.h',
        'printer_cx.c',
        'printer_cx.h',
        'y3.c',
        'y3.h',
        'y3-dll.c',
        'y3-dll.h',
    ],
)
