util_lib = static_library(
    'util',
    include_directories : inc,
    implicit_include_directories : false,
    dependencies : [
        capnhook.get_variable('hook_dep'),
        imagehlp_lib,
    ],
    sources : [
        'async.c',
        'async.h',
        'crc.c',
        'crc.h',
        'dll-bind.c',
        'dll-bind.h',
        'dprintf.c',
        'dprintf.h',
        'dump.c',
        'dump.h',
        'get_function_ordinal.c',
        'get_function_ordinal.h',
        'lib.c',
        'lib.h',
        'slurp.c',
        'slurp.h',
        'str.c',
        'str.h',
        'env.c',
        'env.h',
    ],
)
