sekitoio_lib = static_library(
    'sekitoio',
    name_prefix : '',
    include_directories : inc,
    implicit_include_directories : false,
    dependencies : [
        xinput_lib,
    ],
    sources : [
        'config.c',
        'config.h',
        'backend.h',
        'keyboard.c',
        'keyboard.h',
        'sekitoio.c',
        'sekitoio.h',
    ],
)
