divaio_lib = static_library(
    'divaio',
    name_prefix : '',
    include_directories : inc,
    implicit_include_directories : false,
    dependencies : [
        dinput8_lib,
        dxguid_lib,
        xinput_lib,
    ],
    link_with : [
        util_lib,
    ],
    sources : [
        'divaio.c',
        'divaio.h',
        'config.c',
        'config.h',
        'input/backend.h',
        'input/di.c',
        'input/di.h',
        'input/di-dev.c',
        'input/di-dev.h',
        'input/kb.c',
        'input/kb.h',
        'input/wnd.c',
        'input/wnd.h',
        'input/xi.c',
        'input/xi.h',
        'touch/backend.h',
        'touch/mouse.c',
        'touch/mouse.h',
        'touch/wintouch.c',
        'touch/wintouch.h',
    ],
)
