shared_library(
    'kemonohook',
    name_prefix : '',
    include_directories : inc,
    implicit_include_directories : false,
    vs_module_defs : 'kemonohook.def',
    c_pch : '../precompiled.h',
    dependencies : [
        capnhook.get_variable('hook_dep'),
        capnhook.get_variable('hooklib_dep'),
    ],
    link_with : [
        aimeio_lib,
        amex_lib,
        board_lib,
        hooklib_lib,
        jvs_lib,
        kemonoio_lib,
        platform_lib,
        unityhook_lib,
        util_lib,
    ],
    sources : [
        'config.c',
        'config.h',
        'dllmain.c',
        'hooks.c',
        'hooks.h',
        'jvs.c',
        'jvs.h',
        'kemono-dll.c',
        'kemono-dll.h',
    ],
)
