tokyoio_lib = static_library(
    'tokyoio',
    name_prefix : '',
    include_directories : inc,
    implicit_include_directories : false,
    c_pch : '../precompiled.h',
    dependencies : [
        xinput_lib,
    ],
    sources : [
        'backend.h',
        'config.c',
        'config.h',
        'dllmain.c',
        'tokyoio.h',
        'kb.c',
        'kb.h',
        'xi.c',
        'xi.h',
    ],
)
